### ISSUE TITLE
How to use mimicknet ？

### ISSUE THREAD

**Issue by Jaycee0602** [Ouwen/MimickNet#18]
Hello, how can I improve the resolution of single photos by using the pre-training model? Looking forward to your reply.Thanks.

**Comment by Ouwen** [comment]
Hey Jay, check out this colab notebook: https://colab.research.google.com/drive/1R_ARqpWoiHcUQWg1Fxwyx-ZkLi0IZ5qs

It'll show you how to use the model to post-process a couple ultrasound images

**Comment by Jaycee0602** [comment]
> Hey Jay, check out this colab notebook: https://colab.research.google.com/drive/1R_ARqpWoiHcUQWg1Fxwyx-ZkLi0IZ5qs
> 
> It'll show you how to use the model to post-process a couple ultrasound images

Thanks for your reply. I have run the example in colab. Now I want to use mimicknet to improve a low-resolution image of myself. Is there any way to help me? Thank you.Looking forward to your reply.

**Comment by Ouwen** [comment]
This trained MimickNet is meant to be run on ultrasound images, not natural images.

**Comment by Jaycee0602** [comment]
I'm sorry that you may have misunderstood. I also wanted to enhance the ultrasound image, but the colab example generated a random image, so I asked if mimicknet could be used to enhance another ultrasound image.Thanks for your reply.

**Comment by Ouwen** [comment]
Right, the colab loops through a dataset of images and runs them through keras. If you want to run your own image you can run them through as a numpy array.

So if you have a 512x512 ultrasound image, you need to turn it into a 1x512x512x1 shape, and run `model.predict`

**Comment by Ouwen** [comment]
Closing this issue. The latest colab should show you how to use the model!
